### ISSUE TITLE
Can't sign transactions with generated accounts - failed precheck with status INVALID_SIGNATURE

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-local-node#109]
### Description

NOTE: Using macOS with M1 chipset

What happened: While creating an aliased account from one of the generated accounts, we fail with`failed precheck with status INVALID_SIGNATURE` when calling `TransferTransaction`

Expected to see `TransferTransaction` called successfully and then have an aliased account created

### 1. Generate the local accounts
``` bash
➜  hedera-local-node git:(main) ✗ npx hedera-local start
Starting the docker containers...
Starting the network...
Generating accounts...
---------- Accounts list:
0.0.1004 - 0x7f109a9e3b0d8ecfba9cc23a3614433ce0fa7ddcc80f2a8f10b222179a5a80d6 - 100000 ℏ
0.0.1005 - 0x6ec1f2e7d126a74a1d2ff9e1c5d90b92378c725e506651ff8bb8616a5c724628 - 100000 ℏ
0.0.1006 - 0xb4d7f7e82f61d81c95985771b8abf518f9328d019c36849d4214b5f995d13814 - 100000 ℏ
0.0.1007 - 0x941536648ac10d5734973e94df413c17809d6cc5e24cd11e947e685acfbd12ae - 100000 ℏ
0.0.1008 - 0x5829cf333ef66b6bdd34950f096cb24e06ef041c5f63e577b4f3362309125863 - 100000 ℏ
0.0.1009 - 0x8fc4bffe2b40b2b7db7fd937736c4575a0925511d7a0a2dfc3274e8c17b41d20 - 100000 ℏ
0.0.1010 - 0xb6c10e2baaeba1fa4a8b73644db4f28f4bf0912cceb6e8959f73bb423c33bd84 - 100000 ℏ
0.0.1011 - 0xfe8875acb38f684b2025d5472445b8e4745705a9e7adc9b0485a05df790df700 - 100000 ℏ
0.0.1012 - 0xbdc6e0a69f2921a78e9af930111334a41d3fab44653c8de0775572c526feea2d - 100000 ℏ
0.0.1013 - 0x3e215c3d2a59626a669ed04ec1700f36c05c9b216e592f58bbfd3d8aa6ea25f9 - 100000 ℏ
---------- Total: 10 
```

### 2. Use a generated account to create an aliased account with the following code snippet
```javascript
import {
    Client,
    PrivateKey,
    Hbar,
    AccountId,
    AccountBalanceQuery,
    AccountInfoQuery,
    TransferTransaction,
} from "@hashgraph/sdk";

import dotenv from "dotenv";

dotenv.config();

async function main() {
    let client;

    try {
        client = Client.forName({"127.0.0.1:50211":"0.0.3"}).setOperator(
            AccountId.fromString("0.0.1004"),
            PrivateKey.fromStringED25519("0x7f109a9e3b0d8ecfba9cc23a3614433ce0fa7ddcc80f2a8f10b222179a5a80d6")
        );
    } catch (error) {
        throw new Error(
            "Environment variables HEDERA_NETWORK, OPERATOR_ID, and OPERATOR_KEY are required."
        );
    }

    console.log('"Creating" a new account');

    const privateKey = PrivateKey.generateECDSA();
    const publicKey = privateKey.publicKey;

    const aliasAccountId = publicKey.toAccountId(0, 0);

    console.log("Transferring some Hbar to the new account");
    const response = await new TransferTransaction()
        .addHbarTransfer(client.operatorAccountId, new Hbar(10).negated())
        .addHbarTransfer(aliasAccountId, new Hbar(10))
        .execute(client);
    await response.getReceipt(client);

    const balance = await new AccountBalanceQuery()
        .setAccountId(aliasAccountId)
        .execute(client);

    console.log(`Balances of the new account: ${balance.toString()}`);

    const info = await new AccountInfoQuery()
        .setAccountId(aliasAccountId)
        .execute(client);

    console.log(`The normal account ID: ${info.accountId.toString()}`);
    console.log(`The aliased account ID: 0.0.${info.aliasKey.toString()}`);
    console.log(`The private key (use this in sdk/Hedera native wallets): ${privateKey.toString()}`);
    console.log(`The raw private key (use this for JSON RPC wallet import): ${privateKey.toStringRaw()}`);

    console.log("Example complete!");
    client.close();
}

void main();
```

### 3. Program throws an error at `TransferTransaction()`
```bash
➜  examples git:(main) ✗ node account-alias-ecdsa.js 
"Creating" a new account
Transferring some Hbar to the new account
file:///Users/michaelgarber/hedera-tools/hedera-json-rpc-relay/docs/examples/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:35
        super(
        ^

PrecheckStatusError: transaction 0.0.1004@1657299780.919147360 failed precheck with status INVALID_SIGNATURE
    at new PrecheckStatusError (file:///Users/michaelgarber/hedera-tools/hedera-json-rpc-relay/docs/examples/node_modules/@hashgraph/sdk/src/PrecheckStatusError.js:35:9)
    at TransferTransaction._mapStatusError (file:///Users/michaelgarber/hedera-tools/hedera-json-rpc-relay/docs/examples/node_modules/@hashgraph/sdk/src/transaction/Transaction.js:1413:16)
    at TransferTransaction.execute (file:///Users/michaelgarber/hedera-tools/hedera-json-rpc-relay/docs/examples/node_modules/@hashgraph/sdk/src/Executable.js:697:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///Users/michaelgarber/hedera-tools/hedera-json-rpc-relay/docs/examples/account-alias-ecdsa.js:42:22) {
  status: Status { _code: 7 },
  transactionId: TransactionId {
    accountId: AccountId {
      shard: Long { low: 0, high: 0, unsigned: false },
      realm: Long { low: 0, high: 0, unsigned: false },
      num: Long { low: 1004, high: 0, unsigned: false },
      aliasKey: null,
      aliasEvmAddress: null,
      _checksum: null
    },
    validStart: Timestamp {
      seconds: Long { low: 1657299780, high: 0, unsigned: false },
      nanos: Long { low: 919147360, high: 0, unsigned: false }
    },
    scheduled: false,
    nonce: null
  }
}
```

### Hedera network

other

### Version

v1.0.3

### Operating system

macOS

**Comment by mgarbs** [comment]
Hi @Kalina-Todorova it worked! Thank you and good catch :)
![image](https://user-images.githubusercontent.com/101222532/178475536-a8d8a245-e219-4209-8ce3-36897153e7bf.png)

**Comment by Kalina-Todorova** [comment]
@mgarbs Nice to hear! :)
