### ISSUE TITLE
Error invoking RPC shown while executing tests

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#228]
### Description

When executing tests, I always get this error:
```
[Request ID: 3854533e-3b97-40c5-b531-a1af9776e16a] Error invoking RPC: 
  ProviderError: HttpProviderError
      at HttpProvider.request (/Users/stoyanpanayotov/Dev/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at LocalAccountsProvider.request (/Users/stoyanpanayotov/Dev/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at AutomaticGasPriceProvider._suggestEip1559FeePriceValues (/Users/stoyanpanayotov/Dev/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:232:22)
      at AutomaticGasPriceProvider.request (/Users/stoyanpanayotov/Dev/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:173:34)
      at EthersProviderWrapper.send (/Users/stoyanpanayotov/Dev/hedera-smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
The relay logs have this error:
```
[2022-11-22 11:03:05.657 +0000] ERROR (relay-eth/55 on bc900f8ada6a): [Request ID: 9d358b1a-f111-4f5a-8e41-86e8b7d38ae5] Error raised during getTransactionCount for address 0x05fba803be258049a27b820088bab1cad2058871, block number or tag pending
    err: {
      "type": "SDKClientError",
      "message": "",
      "stack":
          Error
              at SDKClient.<anonymous> (/home/node/app/packages/relay/dist/lib/clients/sdkClient.js:74:40)
              at Generator.throw (<anonymous>)
              at rejected (/home/node/app/packages/relay/dist/lib/clients/sdkClient.js:25:65)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": {
        "_code": 21
      },
      "validNetworkError": false
    }
```

### Steps to reproduce

1. Run local-node
2. Execute tests

### Hedera network

other

### Version

v.2.2.1

**Comment by mshakeg** [comment]
Hi @Kalina-Todorova , this issue seems a bit related to [this one](https://github.com/hashgraph/hedera-json-rpc-relay/issues/645). A fix has been made to the service layer, however the local node still points to an earlier image. I haven't had a chance to set up a config, and was also hoping @dimitrovmaksim would have created a patch release by now so I wouldn't have to.

**Comment by Kalina-Todorova** [comment]
Hi @mshakeg we are delaying an official release with the latest images due to additional testing and cannot provide an ETA right now. Please do let us know if you get the chance to test out.

**Comment by georgi-l95** [comment]
Not reproducible. Closing until we encounter it again.
