### ISSUE TITLE
npx hedera-local start throws an error

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-local-node#24]
Even when docker is started and all docker containers are removed - start throws the errors below:

- <img width="436" alt="image (1)" src="https://user-images.githubusercontent.com/101559469/165477664-492fb33e-5e26-461c-a979-f45961a5dd5c.png">
- <img width="422" alt="image" src="https://user-images.githubusercontent.com/101559469/165477676-46ba960c-97ac-4950-a746-b57e5f314daa.png">

**Comment by jigsnptel** [comment]
hi, can you help me with this ?

npm install --save-dev 'hedera-local'
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/'hedera-local' - Not found
npm ERR! 404
npm ERR! 404 ''hedera-local'@' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404 1. name can no longer contain special characters ("~'!()")
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Vipul\AppData\Local\npm-cache_logs\2022-04-24T14_14_39_786Z-debug-0.log

**Comment by jigsnptel** [comment]
node version 16.14.2
npm version 8.7.0
Docker version 20.10.13, build a224086

**Comment by natanasow** [comment]
@jigsnptel could you try to stop the containers, prune the docker system, and start them again?
```
npx hedera-local stop
docker system prune
npx hedera-local start
```

**Comment by SimiHunjan** [comment]
I started the network by using the `npx hedera-local start` command. 
 Output:
 ```
$ npx hedera-local start
Starting the docker containers...
0.22.0: Pulling from hedera-registry/network-node-haveged
Digest: sha256:b1a72fb60ccd62c3c784630113d178f73f7da572c3a8409d73773eeae1ae4133
Status: Downloaded newer image for gcr.io/hedera-registry/network-node-haveged:0.22.0
docker.io/library/postgres@sha256:7ced77a458b7d6f4f3e4abfa55d6428fdcd0016e1926cb7463250b54b06480a1: Pulling from library/postgres
Digest: sha256:7ced77a458b7d6f4f3e4abfa55d6428fdcd0016e1926cb7463250b54b06480a1
Status: Downloaded newer image for postgres@sha256:7ced77a458b7d6f4f3e4abfa55d6428fdcd0016e1926cb7463250b54b06480a1
latest: Pulling from minio/minio
Digest: sha256:cc3940c643eaf91f8236b51442cf23d386a604a90f23adaf599832005a770253
Status: Downloaded newer image for minio/minio:latest
0.4.0: Pulling from hedera-registry/uploader-mirror
Digest: sha256:f16ecf8ea43d3853c185f71c79b95577ecba75ca4ea5d96e2d19137c31d624c4
Status: Downloaded newer image for gcr.io/hedera-registry/uploader-mirror:0.4.0
0.22.0: Pulling from hedera-registry/main-network-node
Digest: sha256:10c8f031c1c67551847ea37bcb90a5429ceefe1702807a1505c6fadaf4792a7c
Status: Downloaded newer image for gcr.io/hedera-registry/main-network-node:0.22.0
13.5-alpine: Pulling from library/postgres
Digest: sha256:8048dd080d627956cc6d9f49eae706b1e71efadcca33f7b16f7a2357d9ff96ef
Status: Downloaded newer image for postgres:13.5-alpine
0.49.0: Pulling from mirrornode/hedera-mirror-grpc
Digest: sha256:50ddad7e3cb8f96726dd973609a27a7127a61d05feac95991c61bcefad06627e
Status: Downloaded newer image for gcr.io/mirrornode/hedera-mirror-grpc:0.49.0
0.49.0: Pulling from mirrornode/hedera-mirror-importer
Digest: sha256:be253eb7e2b9a11f9b58a2b0f048d23944cecf3f32ac4fcfe7834c2320f54cce
Status: Downloaded newer image for gcr.io/mirrornode/hedera-mirror-importer:0.49.0
0.49.0: Pulling from mirrornode/hedera-mirror-rest
Digest: sha256:1d1c164860573bc6d73f48d9e1fd2913b9be26faccd46c936ed6c09f00aa942f
Status: Downloaded newer image for gcr.io/mirrornode/hedera-mirror-rest:0.49.0
0.49.0: Pulling from mirrornode/hedera-mirror-web3
Digest: sha256:d47492f9de0a6f928ca9df86f470497cd1611d535f0659478d6ae433e68e6920
Status: Downloaded newer image for gcr.io/mirrornode/hedera-mirror-web3:0.49.0
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:5600
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5600
}

Node.js v17.0.1
```
The I tried to use  `npx hedera-local generate-accounts 2` to generate 2 new accounts for the network and received an error.

```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:130:10)
    at ripemd160 (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/hdnode/node_modules/@ethersproject/sha2/lib/sha2.js:11:43)
    at new HDNode (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/hdnode/lib/index.js:77:110)
    at Function.HDNode._fromSeed (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/hdnode/lib/index.js:213:16)
    at Function.HDNode.fromMnemonic (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/hdnode/lib/index.js:220:23)
    at Function.Wallet.fromMnemonic (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/wallet/lib/index.js:307:43)
    at Function.Wallet.createRandom (/Users/simihunjan/node_modules/@hashgraph/hedera-local/node_modules/@hethers/wallet/lib/index.js:271:23)
    at Function.generateAccounts (/Users/simihunjan/node_modules/@hashgraph/hedera-local/src/hederaUtils.js:27:35)
    at /Users/simihunjan/node_modules/@hashgraph/hedera-local/cli.js:41:25 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

**Comment by SimiHunjan** [comment]
Tried with the account option as well and it errors.

```
npx hedera-local start --accounts=2
Starting the docker containers...
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:5600
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5600
}

Node.js v17.0.1
```
