### ISSUE TITLE
Cannot read properties of undefined (reading 'Image')

### ISSUE THREAD

**Issue by 0xankit** [hashgraph/hedera-local-node#347]
### Description

when trying to run `$ hedera start`
```
$ hedera start
Applying local config settings...
Successfully applied local config settings
Starting the docker containers...
TypeError: Cannot read properties of undefined (reading 'Image')
    at Object.callback (/home/user/.nvm/versions/node/v20.3.1/lib/node_modules/@hashgraph/hedera-local/src/helpers/dockerCheck.js:70:33)
    at /home/user/.nvm/versions/node/v20.3.1/lib/node_modules/@hashgraph/hedera-local/node_modules/dockerode/lib/docker.js:435:12
    at Modem.buildPayload (/home/user/.nvm/versions/node/v20.3.1/lib/node_modules/@hashgraph/hedera-local/node_modules/docker-modem/lib/modem.js:359:7)
    at IncomingMessage.<anonymous> (/home/user/.nvm/versions/node/v20.3.1/lib/node_modules/@hashgraph/hedera-local/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

### Steps to reproduce

1. hedera start

### Additional context

```
$ docker --version
Docker version 24.0.2, build cb74dfc

$ hedera --version
2.10.0

$ docker-compose --version
Docker Compose version v2.15.1

$ node --version
v20.3.1

```

### Hedera network

other

### Version

2.10.0

### Operating system

Linux

**Comment by JunsikChoi** [comment]
How did you install docker on your machine?

**Comment by 0xankit** [comment]
```
$ sudo apt update
$ sudo apt install apt-transport-https ca-certificates curl software-properties-common
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
$ echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
$ sudo apt install docker-ce docker-ce-cli containerd.io
```
