### ISSUE TITLE
`npx hedera-local start` does not work

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-local-node#43]
### Description

`npx hedera-local start` errors with the following:

```
SimiHunjan ~ %1npx hedera-local start
Starting the docker containers...
Starting the network...
Generating accounts...
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:130:10)
    at ripemd160 (/Users/simihunjan/node_modules/@hethers/hdnode/node_modules/@ethersproject/sha2/lib/sha2.js:11:43)
    at new HDNode (/Users/simihunjan/node_modules/@hethers/hdnode/lib/index.js:78:110)
    at Function.HDNode._fromSeed (/Users/simihunjan/node_modules/@hethers/hdnode/lib/index.js:214:16)
    at Function.HDNode.fromMnemonic (/Users/simihunjan/node_modules/@hethers/hdnode/lib/index.js:221:23)
    at Function.Wallet.fromMnemonic (/Users/simihunjan/node_modules/@hethers/wallet/lib/index.js:314:43)
    at Function.Wallet.createRandom (/Users/simihunjan/node_modules/@hethers/wallet/lib/index.js:278:23)
    at Function.generateAccounts (/Users/simihunjan/node_modules/@hashgraph/hedera-local/src/hederaUtils.js:27:35)
    at start (/Users/simihunjan/node_modules/@hashgraph/hedera-local/cli.js:67:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}


```

### Steps to reproduce

See above

### Additional context

See above

### Hedera network

other

### Version

latest

### Operating system

macOS

**Comment by Kalina-Todorova** [comment]
Hi @SimiHunjan could you share your Node and NPM versions?
Node version check: `node -v`
NPM version check: `npm -v`
