### ISSUE TITLE
local-node throws `Error invoking RPC: timeout exceeded` right after startup

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-local-node#607]
### Description

After the completion of the local node's startup process, for many times I execute smart contract tests against the local node, it throws the error `Error invoking RPC: timeout exceeded`.

```bash
ProviderError: [Request ID: a6533f50-33b6-473a-aa87-f069bc778c38] Error invoking RPC: timeout exceeded
      at HttpProvider.request (/Users/user/development/hashgraph/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at HardhatEthersSigner.sendTransaction (/Users/user/development/hashgraph/hedera-smart-contracts/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
      at ContractFactory.deploy (/Users/user/development/hashgraph/hedera-smart-contracts/node_modules/ethers/src.ts/contract/factory.ts:111:24)
      at Context.<anonymous> (/Users/user/development/hashgraph/hedera-smart-contracts/test/stateContract.js:38:16)
```

### Steps to reproduce

1. run `npm run start -d`
2. run a smart contract test
3. observe the `timeout exceeded` error. 

### Additional context

Note that it's not consistent, sometimes it works fine but many times it throws `timeout exceeded`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by georgi-l95** [comment]
Fixed with updating to sdk version 2.49.2 in [this](https://github.com/hashgraph/hedera-local-node/pull/723) PR.
